 default: &default
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  adapter: mysql2
  username: root
  password: 2233
  host: localhost
  database: hurima-39604_development

test:
  <<: *default
  adapter: mysql2
  username: root
  password: 2233
  host: localhost
  database: hurima-39604-test

production:
  <<: *default
  adapter: postgresql
  url: <%= ENV['DATABASE_URL'] %>
